version: "3.8"

services:
  client:
    build:
      context: ./client
    image: madesh001/mern-client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: always

  server:
    build:
      context: ./server
    image: madesh001/mern-server
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/BlogApp
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
